# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres
    # environment:
    #   - POSTGRES_USER=${PG_USER:drc}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:drc}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: nlxio/gemma-drc
    environment:
      - DJANGO_SETTINGS_MODULE=drc.conf.docker
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db
  tests:
    build:
      context: ./
      target: jenkins
    volumes:
      - ${WORKSPACE}/reports:/app/reports
    environment:
      - DJANGO_SETTINGS_MODULE=drc.conf.jenkins
      - SECRET_KEY=jenkins
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_HOST=db
    depends_on:
      - db

volumes:
  postgres_data:


  # See: src/drc/conf/docker.py
  # Optional containers below:
#  elasticsearch:
#    # NOTE: No persistance storage configured.
#    # See: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - cluster.routing.allocation.disk.threshold_enabled=false
#    ports:
#      - 9200:9200
#  redis:
#    # NOTE: No persistance storage configured.
#    # See: https://hub.docker.com/_/redis/
#    image: redis
#    ports:
#        - 6379:6379
