openapi: 3.0.0
info:
  title: Mock-Overige-data registratiecomponent (drc) API documentatie
  description: Deze API is GEEN referentie-implementatie van overige services
  contact:
    email: support@maykinmedia.nl
  license:
    name: EUPL 1.2
  version: '1'
security:
  - basic: []
paths:
  /enkelvoudiginformatieobject:
    post:
      operationId: enkelvoudiginformatieobject_create
      description: Registreer een EnkelvoudigInformatieObject.
      responses:
        '201':
          description: ''
      tags:
        - enkelvoudiginformatieobject
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                identificatie:
                  description: >-
                    Een binnen een gegeven context ondubbelzinnige referentie
                    naar het INFORMATIEOBJECT.
                  type: string
                  minLength: 1
                  maxLength: 40
                bronorganisatie:
                  description: >-
                    Het RSIN van de Niet-natuurlijk persoon zijnde de
                    organisatie die het informatieobject heeft gecreëerd of
                    heeft ontvangen en als eerste in een samenwerkingsketen
                    heeft vastgelegd.
                  type: string
                  maxLength: 9
                creatiedatum:
                  description: >-
                    Een datum of een gebeurtenis in de levenscyclus van het
                    INFORMATIEOBJECT.
                  type: string
                  format: date
                titel:
                  description: De naam waaronder het INFORMATIEOBJECT formeel bekend is.
                  type: string
                  minLength: 1
                  maxLength: 200
                auteur:
                  description: >-
                    De persoon of organisatie die in de eerste plaats
                    verantwoordelijk is voor het creëren van de inhoud van het
                    INFORMATIEOBJECT.
                  type: string
                  minLength: 1
                  maxLength: 200
                formaat:
                  description: >-
                    De code voor de wijze waarop de inhoud van het ENKELVOUDIG
                    INFORMATIEOBJECT is vastgelegd in een computerbestand.
                  type: string
                  maxLength: 255
                taal:
                  description: >-
                    Een taal van de intellectuele inhoud van het ENKELVOUDIG
                    INFORMATIEOBJECT
                  type: string
                  minLength: 1
                  maxLength: 20
                inhoud:
                  type: string
                  format: binary
              required:
                - identificatie
                - creatiedatum
                - titel
                - auteur
                - taal
                - inhoud
    parameters: []
  '/enkelvoudiginformatieobject/{id}':
    get:
      operationId: enkelvoudiginformatieobject_read
      description: Geef de details van een EnkelvoudigInformatieObject.
      responses:
        '200':
          description: ''
      tags:
        - enkelvoudiginformatieobject
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this informatieobject.
        required: true
        schema:
          type: integer
servers:
  - url: /api/v1
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
